### ISSUE TITLE
Defining databases in WAM

### ISSUE THREAD

**Issue by henhuy** [rl-institut/WAM#1]
Within this issue, I want to discuss multiple minor ideas about database integration in the WAM.

1. Engine Name:
Right now,WAM  _settings.py_ loads `DEFAULT` database config from `CONFIG_PATH` `[DATABASES]` section. Afterwards, `'django.db.backends.'` is added in front of `ENGINE` name. The idea behind that, was to allow one setup for both Django ORM and SQLAlchemy (I connect to same db from both ORMs), as SQLAlchemy requires engine as _posstgresql_ and django as _django.db.backends.postgresql_. Maybe we should change that to full engine name, to avoid "magic" string manipulation within code.

2. WAM-default database:
My app only needs _django.db.backends.postgresql_ engine. But stemp_abw app for example needs _django.contrib.gis.db.backends.postgis_. As the latter one works for both cases, I would set up this engine as our default engine. Okay?

3. Multiple databases simultaneously:
In django, it is also possible to run multiple dbs in parallel. Therefore, database routers have to be set up, which map models to specific databases (see https://docs.djangoproject.com/en/2.1/topics/db/multi-db/). But using this technic, could get us into some pitfalls, as database migration has to be performed on all databases and cross-relations are difficult. So maybe we should avoid it until it's deeply necessary. D'accord?

**Comment by nesnoj** [comment]
> 1. Engine Name:
>    Right now,WAM  _settings.py_ loads `DEFAULT` database config from `CONFIG_PATH` `[DATABASES]` section. Afterwards, `'django.db.backends.'` is added in front of `ENGINE` name. The idea behind that, was to allow one setup for both Django ORM and SQLAlchemy (I connect to same db from both ORMs), as SQLAlchemy requires engine as _posstgresql_ and django as _django.db.backends.postgresql_. Maybe we should change that to full engine name, to avoid "magic" string manipulation within code.

I'd like to avoid magic stuff like this as well. But I wasn't aware of the double-ORM-advantage the short version brings. But I guess this doesn't work for `postgis` as used in stemp-abw anyway?

> 2. WAM-default database:
>    My app only needs _django.db.backends.postgresql_ engine. But stemp_abw app for example needs _django.contrib.gis.db.backends.postgis_. As the latter one works for both cases, I would set up this engine as our default engine. Okay?

Agree

> 3. Multiple databases simultaneously:
>    In django, it is also possible to run multiple dbs in parallel. Therefore, database routers have to be set up, which map models to specific databases (see https://docs.djangoproject.com/en/2.1/topics/db/multi-db/). But using this technic, could get us into some pitfalls, as database migration has to be performed on all databases and cross-relations are difficult. So maybe we should avoid it until it's deeply necessary. D'accord?

Generally yes, but I there will definitely be apps which do not use the default DB for django's model-related tables. For example in your app, @jh-RLI, right? if I'm not mistaken, @jh-RLI used OEP tables for the models?!
I agree to leave it as it is as long as it's possible to redefine the model tables manually. Does this work?

**Comment by henhuy** [comment]
> But I guess this doesn't work for postgis as used in stemp-abw anyway?

You are right! So, this approach isn't helpful - I will change settings to ask for full-engine-name.

> For example in your app, @jh-RLI, right?

As I understood, @jh-RLI doesn't need djangos ORM for his models by now (he will use SQLAlchemy instead). But with supposed database routers, he would be able to do so for his app. **BUT**, the docker-wam cannot automatically migrate to different databases _by now_ - this has to be done by hand. It could be tricky to integrate such a solution - so I wanted to be sure, if we really need it.

> as it is as long as it's possible to redefine the model tables manually

What do you mean exactly? Is it covered by my explanation above?

**Comment by jh-RLI** [comment]
@nesnoj yes you are right. Currently my app_eGoVIS only depends on the ORM derived from the OEP tables. 
@henhuy I also agree with the subjects 1 and 2 ( my app also uses django.contrib.gis.db.backends.postgis). About 3. it seems like you already know my answer :). But i thought I still need to use Django ORM for the admin page related stuff. 
I think what I really need is just the connection to the OEP.

**Comment by henhuy** [comment]
Pushed new engine name implementation -> 8ad8e54ec01825a7a1e11d88f83c53cb0bd419f7
Will set up wam to use it as well.
