### ISSUE TITLE
Move source highlight JS to WAM

### ISSUE THREAD

**Issue by nesnoj** [rl-institut/WAM#10]
Please add the source highlight JS to WAM, you can find the snippet in [this](https://github.com/rl-institut/WAM_APP_stemp_abw/blob/e5f010ade6b6a83f72c772b8da39de60d544abc6/static/stemp_abw/foundation/js/app.js) file starting at **line 42452** (unfortunately the file is too lange to be shown on github). Dunno if additional JS lib imports are required.

```
jquery__WEBPACK_IMPORTED_MODULE_0___default()(document).ready(function () {
  // if there is '#source' in URL, find source ID and highlight source
  if (window.location.href.indexOf("#source") > -1) {
    var URL = window.location.href;
    var sourceID = URL.split('#')[1];
    jquery__WEBPACK_IMPORTED_MODULE_0___default()('#' + sourceID).effect("highlight", {}, 5000);
  }
});
```

A single source is highlighted using URL like `.../<APP>/sources/#source-1`, a source category using `.../<APP>/sources/#source-category-1`

**Comment by henhuy** [comment]
Implemented for source.
Changed url to use simple id: `.../<APP>/sources/6`

**Comment by henhuy** [comment]
Source or category can be highlighted.
Changed url a bit. Try with:
`.../<APP>/sources/source-1`
`.../<APP>/sources/category-1`

**Comment by nesnoj** [comment]
482692308bb39e678628317ac9eb692e3d2733b5 removes superfluous jQuery var.
Caution: Works with recent foundation versions only, may cause problems with older versions.
Tested with current master https://github.com/zurb/foundation-zurb-template/tree/878b7ff28e24a4ad5b3508420d2297fcc6f2c90e

**Comment by nesnoj** [comment]
Currently not working, e.g. `<BASE_URL>/sources/#source-1`
The `highlight_id` is None in the view:
https://github.com/rl-institut/WAM/blob/845c5a8964fd32024d21843ddcfa02f5354ab17c/meta/views.py#L69

**Comment by henhuy** [comment]
Url-format is now:
<BASE_URL>/sources/?source=1

**Comment by nesnoj** [comment]
Ah, this seems to have changed in the last refactoring. Cheers!
