### ISSUE TITLE
Ghostery replaces Mapbox token

### ISSUE THREAD

**Issue by nesnoj** [rl-institut/WAM#100]
WAM apps which include mapbox tiles (FRED+ABW) use a token for authentication which is modified by the browser extension Ghostery to https://api.mapbox.com/[...]?access_token=ghostery. This results in responses like "...status of 401 (Unauthorized)" and tiles aren't loaded.

This bug is quite annoying, especially because you're not informed but the tiles are just not showing up. Not sure how many people make use of Ghostery. There's an [issue](https://github.com/mapbox/mapbox-gl-js/issues/8894) in the mapbox repo but of course, there's nothing they can do about it.

I tried 3 different Browser+Ghostery configs:
  - Chromium 63.0.3239.84 + Ghostery 8.4.8: **Doesn't work**
  - FF 57.0.4 + Ghostery 8.4.6: **OK**
  - Chrome  60.0.3112.101 + Ghostery 8.4.8: **OK**

I wonder if this is due to my very (!) outdated Browsers only. Does anyone of you use Ghostery and could try whether the map tiles are loaded in the [StEmp-ABW Tool](https://wam.rl-institut.de/stemp_abw/app/)?

**Comment by christian-rli** [comment]
I don't normally use ghostery (i'm using ublock origin, which I can recommend), but I installed it into my firefox. Tiles load without any issues.

**Comment by nesnoj** [comment]
As this seems very system specific and probably does not affect many users, I close this one.
