### ISSUE TITLE
Info of WAM_APPS is loaded from ENV and not from config file

### ISSUE THREAD

**Issue by 4lm** [rl-institut/WAM#13]
Hi @henhuy, as spoken, as short reminder as an issue. Info of WAM_APPS is loaded from ENV and not from the config file.

**Comment by henhuy** [comment]
I tried to change it, but it is not possible with our docker setup as the config file is mounted into container and thus, not present when docker image is built. So unfortunately, this cannot be changed. Would have been nice, but I think it's not so important...
So I will close this issue now.
