### ISSUE TITLE
Add Options Section to config file (DB connection)

### ISSUE THREAD

**Issue by jh-RLI** [rl-institut/WAM#20]
Django Implements the Options field. With this field you can change the default schema which is public in postgresql - to another schema. I tried to insert the OPTIONS to my config file but i get a type error.
I found a workaround for that by just inserting the line after the config file is loaded in the settings.py.  

How i tested it:
[DATABASES]
    [[DEFAULT]]
        ENGINE = django.contrib.gis.db.backends.postgis
		OPTIONS = {options: -c search_path=grid}
        NAME = oedb
        ..............

Error:
TypeError: 'str' object is not a mapping

How django implements this:
DATABASES = {
'default': {
    'ENGINE': 'django.db.backends.postgresql_psycopg2',
    **'OPTIONS': {'options': '-c search_path=SCHEMA_NAME'},**
    'NAME': 'multi_schema_db',
    'USER': 'tester',
    'PASSWORD': 'lol so easy',
    'HOST': 'localhost'
},

**Comment by henhuy** [comment]
Hey Jonas,

but this option would move ALL tables to the specified schema.
This is not an option for the WAM-server.
But maybe we could implement the option field to have it locally (not prio 1, I would say)

Why do you want to have it? You could simply add a new database locally... 
(this is recommended - schema-like databases are possible, but not always useful in the end).

**Comment by nesnoj** [comment]
@jh-RLI Can we close this one?

**Comment by jh-RLI** [comment]
Yes, sqlalchemy is used to query other db/schema.
