### ISSUE TITLE
There is no visible CI in place

### ISSUE THREAD

**Issue by Bachibouzouk** [rl-institut/WAM#23]
We could (should?) setup CI for the WAM repository and begin to lint the code at first. Then we can slowly implement tests. 

I propose that we choose one of 
* https://travis-ci.org/
* https://circleci.com/ (I worked with this one so it might be more easy to setup)

@rl-institut/wam-team : let me know which one you prefer in the comments below :)

The easiest test to implement are on the `models`, but the `views` can also be tested: https://docs.djangoproject.com/en/2.1/intro/tutorial05/

**Comment by christian-rli** [comment]
I don't have a preference, since i'm completely new to continuous integration, so i'll go with whatever the majority here prefers. On another note, I highly approve of the initiative.

**Comment by nesnoj** [comment]
Thanks for getting back to this. Although I've never set up testing, I prefer travis as it is used in other projects such as [oemof](https://github.com/oemof/oemof) and [ding0](https://github.com/openego/ding0).

**Comment by nesnoj** [comment]
@boltbeard has some recent experience with travis, so he might be able to help out if we get stuck..

**Comment by Bachibouzouk** [comment]
@nesnoj : as oemof uses travis, it might make more sense to implement it then. I'll wait a bit more for others feedbacks before I start implementing it :)

**Comment by jh-RLI** [comment]
I dont´t have a preference and also no experience with testing. So same for me: I will be happy to go with whatever the majority here prefers.

**Comment by boltbeard** [comment]
> 
> 
> @boltbeard has some recent experience with travis, so he might be able to help out if we get stuck..

Typically there were very very stupid reasons I chose travis:

- Travis was already being used in other open_eGo repositories (oep) which is handled by a pair of good IT specialists in Magdeburg that we are in contact with.
- Travis is based in Berlin, so their servers are mostly close to where we are, so lesser problems with data transfer and GDPR (not that it would affect ding0 ever)
- Travis' support is really good (but I have not contacted any other CI service, so take this reason with a kilo of salt), maybe as they are based in Berlin they may be fluent in German too.
- Travis is one of the oldest services around so they have some reputation, it is pretty well known in the open source community
- They typically run the tests on Linux servers, all I needed.

Some cons of Travis

- They still use very very old versions of Ubuntu LTS (Xenial-future version, Trusty-Default now, Precise-optional legacy) as the default virtual box which is like 3 years old. One will start to face some trouble while developing things for futuristic versions of python i.e. py 3.7 but these do have work arounds

**Comment by Bachibouzouk** [comment]
Thanks @boltbeard :)

For what it is worth: one of my friend told me that she used Travis because it was easier to find how to use it with conda than for CircleCI. 

@rl-institut/wam-team - If no one rises against this decision, I think I'll implement Travis (for me personally it is a plus as I get to learn something new).

**Comment by 4lm** [comment]
I used Travis in small projects and it worked for me. They lately seem to have problems. They were bought back in January. Many employees have been fired or resigned since then. They seem to have infrastructure problems, e. g. last week or so they suffered a longer outage.

https://devclass.com/2019/03/29/travis-ci-users-left-hanging-as-platform-lies-down/
https://www.heise.de/developer/meldung/Idera-uebernimmt-Travis-CI-4285790.html

I don't know CircleCI, so I would also vote for Travis (because personally I had good experiences with it). But maybe we have to switch later in the process (if we run into issues), which doesn't seem to be a biggy in my eyes.

**Comment by Bachibouzouk** [comment]
Travis is active for linting tests on both `dev` and `master` since #48 , @christian-rli added the build gif in 6d74b59c2743dfc9c4b439b40d6b29b98b03f3e6, I therefore close this issue.
