### ISSUE TITLE
There is no LICENSE file for the project

### ISSUE THREAD

**Issue by Bachibouzouk** [rl-institut/WAM#33]
@Ludee @christian-rli , I presume it would be AGPL3?

**Comment by christian-rli** [comment]
Yes. For that we will need to make sure to reference the source code within the site somewhere to comply with the license: "source code must be distributed along with web publication" https://tldrlegal.com/license/gnu-affero-general-public-license-v3-(agpl-3.0). I don't think that this is the case right now.

**Comment by nesnoj** [comment]
Agree on AGPL3.
Good point, @christian-rli. According to the AGPL3 fulltext, a link to this repo should be sufficient.
But does every app that uses the wam need this link?
If so, it could be included in the legal statement / contact page as it seems to be the only common page included in all apps (at least should be included).

**Comment by christian-rli** [comment]
As far as I understand, there should be a link for every app that is also under AGPL, which is probably not the case for most apps (but only due to a lack of diligence, I suppose). In any case I don't think it hurts, when it's always linked. Only we need to make sure that there is no confusion between source code/license of the app and WAM core itself.

**Comment by nesnoj** [comment]
Ok, so in the [imprint](https://wam.rl-institut.de/impressum/) we need something like

1. "Die hier bereitgestellte Webanwendung verwendet die Software "Web Application & Maps" (WAM) des Reiner Lemoine Instituts, deren Quellcode Sie [hier](https://github.com/rl-institut/WAM/) einsehen und herunterladen können (GNU AGPL 3.0)."

2. Ggf. "Die hier bereitgestellte Webanwendung steht unter der Lizenz XXX....Quellcode hier"

The app-specific rights/license could be fed into the imprint template via context.

**Comment by Bachibouzouk** [comment]
@nesnoj - could you modify the imprint using the branch of #44? I am not sure what you mean by
> fed into the imprint template via context.

**Comment by Bachibouzouk** [comment]
Closed by #44
