### ISSUE TITLE
All team member can merge to master without a review from another developper

### ISSUE THREAD

**Issue by Bachibouzouk** [rl-institut/WAM#35]
It could be a safe practice to forbid direct push to master and to require an approval from an another person before being able to merge to master from a pull request (@Ludee, @christian-rli - this can be set in the repository's settings but I don't have the admin rights it is).

**Comment by christian-rli** [comment]
I adapted the settings. Should i set the default branch to dev while I'm at it? What's the convention there?

**Comment by nesnoj** [comment]
There's no real convention yet as @henhuy was the master of maintenance till now.

Seems to be the right time to get settled :). I propose to use a branching model similar to the one by [Vincent Driessen](https://nvie.com/posts/a-successful-git-branching-model/) (although I don't think we need a separate release branch yet).
dev should be the default and master only updated for releases and hotfixes.
What do you think?

Concerning the review: Approvals / merges to master / releases should be done by people who have a sufficient knowledge of the WAM server side as I'm not sure if this can be treated separately (in theory yes, actually: dunno).

**Comment by christian-rli** [comment]
Ok. I set the dev branch as default. 

Driessen is our institute's standard branching model, so I'd definitely go with that. And I agree with your thoughts on the approvals, although I do not think it to be much of a problem, since not many people will dare to touch the WAM code anyhow.

**Comment by nesnoj** [comment]
> since not many people will dare to touch the WAM code anyhow.

Yea, guess so.

**Comment by Bachibouzouk** [comment]
@christian-rli has taken care of this issue, now one review is required to merge into master or dev
