### ISSUE TITLE
There is no visible Travis build status in the README.md

### ISSUE THREAD

**Issue by Bachibouzouk** [rl-institut/WAM#45]
@christian-rli  you have the rights to perform this :
https://help.github.com/en/enterprise/2.16/admin/developer-workflow/continuous-integration-using-travis-ci

**Comment by christian-rli** [comment]
Added Markdown from Travis-CI like described [here](https://help.github.com/en/enterprise/2.16/admin/developer-workflow/continuous-integration-using-travis-ci).
