### ISSUE TITLE
RTD documentation for apps

### ISSUE THREAD

**Issue by nesnoj** [rl-institut/WAM#47]
There're WAM docs in place [on RTD](https://wam.readthedocs.io) that cover the WAM itself without apps or API. Now I'd like to add one for my app.

I created some sphinx [docs](https://stemp-abw.readthedocs.io) and want the API to be included. Usually, for packages you (or RTD) create it using `sphinx-apidoc` pretty straightforward or it is invoked automatically by including the sphinx.autodoc module.

As our apps need the WAM (more precisely, the django config), it's a little more complicated. After some research (there're heaps of how-tos on sphinx & django but just a few mention docs for django apps only) I added some [manual config](https://github.com/rl-institut/WAM_APP_stemp_abw/commit/57b01330289088a1f5b686de4dec6d2b32aafb46) which works locally but RTD throws import errors.

So I tried to add the WAM package to a [RTD requirements](https://github.com/rl-institut/WAM_APP_stemp_abw/blob/dec35c9a17940e19538b0a08cb9acadd32f54c73/requirements_rtd.txt) file which includes `git+https://github.com/rl-institut/WAM@master#egg=wam` but apparently we do not have a setup.py yet.

I'd like to add one to allow for the WAM installation. Any objections or hints, @rl-institut/wam-team?
Alternatively, there might be better solutions I'm not aware of? Has anyone of you worked with sphinx and standalone django apps before?

**Comment by christian-rli** [comment]
I have no objections re packaging, but no hints either.

**Comment by Bachibouzouk** [comment]
Could [django-sphinxdoc](https://readthedocs.org/projects/django-sphinxdoc/) help? I unfortunately didn't work with sphinx and standalone django apps before :(

**Comment by 4lm** [comment]
Good idea, making the WAM installable via setup.py, we than could make it even installable as PYPI-Package! I have only little experience with setting up setup.py's.

> I'd like to add one to allow for the WAM installation. Any objections or hints, @rl-institut/wam-team?

No objections. No hints.

> Alternatively, there might be better solutions I'm not aware of?

Don't know of any viable alternatives, going the setup.py route seems the way to go.

> Has anyone of you worked with sphinx and standalone django apps before?

No.

**Comment by nesnoj** [comment]
Thanks for the comments. I'll create a setup.py in a new branch soon. New issue: #49

@Bachibouzouk django-sphinxdoc seems to be for integration of docs into the django project i.e. providing our docs on the WAM server - I like this idea, we could talk about it again later, for now I'd leave it on RTD..

I leave this open until we've found and documented a proper solution..

**Comment by nesnoj** [comment]
Fixed in #82 :rocket:
