### ISSUE TITLE
Packaging and distribution

### ISSUE THREAD

**Issue by nesnoj** [rl-institut/WAM#49]
To allow for proper distribution, versioning, meta etc. it'd be great to create a wam package on [PyPI](https://pypi.org). 

Tasks (feel free to amend if I missed something..):
- [ ] Define package name
- [ ] Add setup.py and make sure [requirements](https://docs.python.org/3.7/distutils/) are fulfilled
- [ ] Rename app `wam`
- [ ] Release on PyPI
- [ ] Write a "How-to-release" (large parts can be taken from our existing projects [oemof](https://github.com/oemof/oemof/wiki/How-to-release) and [ego.io](https://github.com/openego/ego.io/wiki/How-to-release)) considering the branching model we agreed on.

Questions @rl-institut/wam-team:
1. Package name (@Bachibouzouk and me favor `wam` (seems to be [available on PyPI](https://pypi.org/search/?q=wam)) -> app `wam` must be renamed which imho makes sense anyway).
2. Rename app `wam`to ...? Proposal: `core` 
3. Location of the "How-to-release": Wiki or Docs? (to my mind it rather belongs to the wiki, but what do you think?)
4. Account for releases on PyPI. I see 2 ways here:
  a) One user creates the project and adds other users as collaborators (as done before in other packages)
  b) Use a new central RLI account for PyPI (add other users as maintainers) to make sure access will be always available in the future (Side note: although due to the collaborator concept this is not an issue in this case, we faced this issue on other platforms, e.g. [zenodo](https://zenodo.org/) where one user is the master of everything).  This way also clearly shows the authorship of the package (RLI).

**Comment by christian-rli** [comment]
packaging name: django-wam

**Comment by Bachibouzouk** [comment]
`core` +1

**Comment by henhuy** [comment]
In my opinion, making the wam a python package isn't very useful.
As far as I know, django apps are packaged, but not the core itself?!

What would be the workflow?
1. Install core via pip
1. How to add app to the core afterwards? In order to do so, one would have to edit installed package manually.

In my understanding, providing Dockerfile and docker-compose.yml is the way to provide easy setup of the WAM for users...

**Comment by henhuy** [comment]
Considering #47 maybe this is indeed the easiest way to create a simple setup.py to enable RTD to build WAM and apps to create the API (I will check if there are other workarounds).

But I still see no advantages for other users when adding to PyPI...

**Comment by nesnoj** [comment]
> Considering #47 maybe this is indeed the easiest way to create a simple setup.py to enable RTD to build WAM and apps to create the API (I will check if there are other workarounds).
> 
> But I still see no advantages for other users when adding to PyPI...

API docs fixed in #82, release via PYPI discontinued. I'll close this one, please reopen if needed.
