### ISSUE TITLE
Move app icons from WAM to apps

### ISSUE THREAD

**Issue by nesnoj** [rl-institut/WAM#56]
App icons for the landing page are located in the WAM repo in [`static/img/`](https://github.com/rl-institut/WAM/tree/9864b7adf96e86ca9cbe14b1d2fcc6d183c6a059/static/img), the path is specified in each app's `app.cfg` ([example](https://github.com/rl-institut/WAM_APP_stemp_abw/blob/34181461ad10aeaa0e202519ea2126b128056d87/app.cfg)).
This leads to unnecessary WAM updates (-> downtimes, hotfixes, ..) and is not in line with the "keep-app-files-and-config-in-app-repo" logic we adhere to.
Hence, the icon files should be moved to the apps, the path given in `app.cfg` could be relative to the app root.

PS: We should consider to create a dir in each app which holds all WAM config stuff (settings.py, app_settings.py, app.cfg, icon).

**Comment by 4lm** [comment]
Sounds good! I support this!

**Comment by Bachibouzouk** [comment]
Me too

**Comment by henhuy** [comment]
yes - this should be changed!
I can do the changes...

**Comment by nesnoj** [comment]
Great! But changes must not be merged earlier than tomorrow afternoon (after the WS)

**Comment by nesnoj** [comment]
Any progress here @henhuy ?

**Comment by nesnoj** [comment]
**Update:**

Instead of using
`icon = 'img/app_stemp_abw_icon.png'`
you can simply use an icon file from the app's static files like
`icon = 'stemp_abw/img/app_stemp_abw_icon.png'`
since they are loaded by the WAM.

Too easy. [Changed this in my app](https://github.com/rl-institut/WAM_APP_stemp_abw/commit/ff64e6515ad84778fbc9d271a496b7c5557ce04f)

@henhuy I remove the app icons from the [WAM img folder](https://github.com/rl-institut/WAM/tree/dev/static/img), ok?
