### ISSUE TITLE
standard for docstring format

### ISSUE THREAD

**Issue by nesnoj** [rl-institut/WAM#6]
Which docstring format do we want to use? There're not many of them yet so it does make sense to discuss this now. I favor the [numpy](https://github.com/numpy/numpy/blob/master/doc/example.py) style over reST, Google or Epytext. In recent projects, we used Sphinx extension napoleon to allow for more datatypes ([example](https://github.com/openego/eDisGo/blob/a301516e3249545a60b80991187b30c733abc13d/edisgo/flex_opt/curtailment.py)).

And you?

PS: @henhuy: I cannot add tags, assignees etc. to issues, could you grant more permissions to me or WAM group in general?

**Comment by nesnoj** [comment]
cheers!

**Comment by henhuy** [comment]
I'm fine with numpy.
Do you always have to use 
> text: :obj:`str`

when using napoleon? No simple `text : str`?
Anyway - for me it's okay too! Main thing is, that we agree on a standard...

**Comment by nesnoj** [comment]
No, for buildin-types you can use `text : str` as well which I try to stick to. Only for external packages or references within the package itself classifiers such as `:obj:` or `:class:` are needed.

Ok, then numpy is the new standard.
