### ISSUE TITLE
Add down-for-maintenance page

### ISSUE THREAD

**Issue by nesnoj** [rl-institut/WAM#60]
Whenever the WAM is down for maintenance, the user gets a 502. There's a need for a "down for maintenance" page.
In most cases, the WAM docker is down during updates etc. so the solution needs to be on webserver level.

@henhuy Any ideas/hints?

**Comment by 4lm** [comment]
- Or maybe rolling updates with docker swarm (swarm would have to be implemented first): https://container-solutions.com/rolling-updates-with-docker-swarm/

- Or (very simple) on domain level a temporary redirect to a static status/maintenance page (maintenance.wam.rl-institut.de or status.wan.rl-institut.de) - could be hosted on netlify.com - with this solution even the server can go down and we have status/maintenance page to show for ...

**Comment by nesnoj** [comment]
> * Or maybe rolling updates with docker swarm (swarm would have to be implemented first): https://container-solutions.com/rolling-updates-with-docker-swarm/

Sounds perfect but I don't think there's time for this right now.

> * Or (very simple) on domain level a temporary redirect to a static status/maintenance page (maintenance.wam.rl-institut.de or status.wan.rl-institut.de) - could be hosted on netlify.com - with this solution even the server can go down and we have status/maintenance page to show for

Good idea, does it provide a maintenance page even if the entire server is down?

In general:
We either could go for a page that works even if the entire server is down or just a page which shows up if the WAM dockers are down. I think the 2nd one would be sufficient right now.. but if there's a free service that serves a custom site during server downtimes, I'd be happy too ;)

**Comment by nesnoj** [comment]
502 test page for caddy was implemented successfully. Next step is to give it a nice design (use 404 page introduced in #70)

**Comment by nesnoj** [comment]
Created and uploaded!

Whenever a 502 is raised (i.e. the dev or prod docker is unreachable because of reboot, recreation etc.), Caddy now serves the following page:

![wam_502_page](https://user-images.githubusercontent.com/15910173/60762070-a7d71380-a057-11e9-9f86-cb6d0b770001.png)
