### ISSUE TITLE
Get rid of highcharts js

### ISSUE THREAD

**Issue by nesnoj** [rl-institut/WAM#78]
As discussed yesterday, the highcharts src must be removed from repo as it conflicts with GPL:
```
Although Highsoft's software have open source codes, our software is not licensed
as an open source software and is unfortunately not compatible with any open
source software license like Apache 2 or any GPL
```
([source](https://shop.highsoft.com/faq))

I do not like using external 3rd-party scripts as it 1) slows down the page, 2) can introduce malware etc. and 3) allows this party to track the usage. But I don't have a better solution right now.

I [replaced](https://github.com/rl-institut/WAM_APP_stemp_abw/commit/0d3208014c24c4405d61302e7c2deeec9acf9d79) the import from static files with official sources in StEmp ABW. I used v7.0.3 (same is in out static files) to make sure the app won't break in future hc releases.

@henhuy, StEmp MV has got multiple imports, could you replace them as well?
We do not have other apps which use hc, right?

BTW, foundation and jquery are MIT licensed so we don't run into problems by including the src..

**Comment by nesnoj** [comment]
Every second attempt to use [StEmp ABW](https://wam.rl-institut.de/stemp_abw/app/), the entire page **lags or does not even show up (waiting for..)** due to the external loading!
It's really annoying...

**Comment by henhuy** [comment]
Ideas?

**Comment by nesnoj** [comment]
As just discussed on the phone, an alternative way is to
- completely remove the HC js from WAM
- keep the HC js files - completely independent from the WAM - somewhere on our webserver (with WAM IP access restriction) and obtain the files in the tools via https
- add a config var which determines the files source (highcharts server or own server) or
**even better**: tool checks if it's running on the WAM (e.g. using the [IP or hostname](https://stackoverflow.com/questions/166506/finding-local-ip-addresses-using-pythons-stdlib)) and uses the appropriate server - what do you think @henhuy?

**Comment by nesnoj** [comment]
Due to lack of time I cannot implement this. What about you @henhuy?
If not, I'd skip it for now

**Comment by nesnoj** [comment]
As soon as you switched to external HC (commit in StEmp ABW: https://github.com/rl-institut/WAM_APP_stemp_abw/commit/0d3208014c24c4405d61302e7c2deeec9acf9d79), feel free to merge #85 and close this issue.

**Comment by nesnoj** [comment]
The described lags seem to be browser-related.
I like the local solution above but due to low priority I'll close this issue. Feel free to reopen if needed.
