### ISSUE TITLE
Release v0.1.3

### ISSUE THREAD

**Issue by nesnoj** [rl-institut/WAM#88]
As the UNECE event is going to take place on Sep 25th, I'll prepare a new StEmp ABW release next week #87. To make it work - esp. i18n - a WAM release is required.

If you don't have objections @Bachibouzouk @christian-rli @henhuy, I'll release v0.1.3 at the beginning of next week (I'll review and integrate #82 before).

Is there anything else you want to have released?

**Comment by henhuy** [comment]
Just checked it out and tested my app - I'm fine!

**Comment by christian-rli** [comment]
Just checked as well. No objections from my end.

**Comment by nesnoj** [comment]
@henhuy, last week you said that you recently updated the WAM install docs in StempMV. Could you amend the WAM install docs accordingly for this release?

**EDIT:** Postponed

**Comment by nesnoj** [comment]
This waits for #89 and the new BMBF logo in StEmp MV @henhuy

**Comment by henhuy** [comment]
> @henhuy, last week you said that you recently updated the WAM install docs in StempMV. Could you amend the WAM install docs accordingly for this release?
> 
> **EDIT:** Postponed

I just add it...

**Comment by nesnoj** [comment]
Done.
Thanks for contributing! :tada:

**Comment by henhuy** [comment]
Nice work! Thank you very much @nesnoj
