### ISSUE TITLE
Remove dependency UserSession from WAM

### ISSUE THREAD

**Issue by nesnoj** [rl-institut/WAM#9]
In sessions, you import UserSession from stemp MV:

https://github.com/rl-institut/WAM/blob/0591e455cb62435c9025cf4dcdd5928b1662cf98/wam/sessions.py#L1

I'd like to use WAM's sessions module so I'd really appreciate if you removed this dependency.
Thank you!

**Comment by henhuy** [comment]
I'm right in the middle of changing my sessions.
Next push will solve it.

**Comment by nesnoj** [comment]
Cheers :+1:
